spring:
  application:
    name: crossplane-service
  cloud:
    discovery:
      enabled: true
      blocking:
        enabled: false
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: cb-fallback
#          uri: http://as-gateway-service.bank.tanzu
#          uri: http://10.195.9.50:32000 # fallback region gateway
          uri: http://10.195.9.180:80
          predicates:
            - Path=/accounts/**,/portfolio/**,/logout/**,/login/**,/users/**
        - id: any-request # regional-svc gateway
#          uri: http://regional-gateway-service.bank.tanzu
#          uri: http://10.195.9.59:32000
          uri: http://10.195.9.200:80
          predicates:
            - Path=/**
  sleuth:
    enabled: true
    sampler.probability: 1
  zipkin:
    enabled: true
wavefront:
  application:
    service: crossplane-ac-service


#logging:
#  level:
#    reactor:
#      netty: INFO
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
