spring:
  cloud:
    discovery:
      enabled: true
      blocking:
        enabled: false
    gateway:
      enabled: true      
      discovery:
        locator:
          enabled: true
      routes:
      - id: quotes-service-curl
        uri: http://quotes-service
        predicates:
        - Path=/quotes/**
        filters:
        - RewritePath=/quotes/(?<path>.*), /$\{path}
      - id: quotes-service
        uri: http://quotes-service
        predicates:
        - Path=/v1/**
      - id: accounts-service
        uri: http://accounts-service
        predicates:
        - Path=/accounts/**
        filters:
        - name: CircuitBreaker
          args:
            name: reg-fallback
            fallbackUri: forward:/fallback
        #filters:
        #- RewritePath=/accounts/(?<path>.*), /$\{path}
      - id: user-service
        uri: http://user-service
        predicates:
        - Path=/users/**
        #filters:
        #- RewritePath=/user/(?<path>.*), /$\{path}
      - id: user-service-login
        uri: http://user-service
        predicates:
        - Path=/login/**
      - id: user-service-logout
        uri: http://user-service
        predicates:
        - Path=/logout/**
      - id: portfolio-service
        uri: http://portfolio-service
        predicates:
        - Path=/portfolio/**
        #filters:
        #- RewritePath=/portfolio/(?<path>.*), /$\{path}
      - id: analytics-service
        uri: http://analytics-service
        predicates:
        - Path=/analytics/**
        #filters:
        #- RewritePath=/analytics/(?<path>.*), /$\{path}
      - id: reg-fallback
        uri: http://10.195.9.50:32000
        predicates:
          - Path=/fallback
  sleuth:
    enabled: true
    sampler.probability: 1
  zipkin:
    enabled: true
        
