spring:
  cloud:
    discovery:
      enabled: true
      blocking:
        enabled: false
    gateway:
      enabled: true      
      discovery:
        locator:
          enabled: true
      routes:
      - id: quotes-service-curl
        uri: ${QUOTES_EP}
        predicates:
        - Path=/quotes/**
        filters:
        - RewritePath=/quotes/(?<path>.*), /$\{path}
      - id: quotes-service
        uri: ${QUOTES_EP}
        predicates:
        - Path=/v1/**
      - id: accounts-service
        uri: ${ACCOUNT_EP}
        predicates:
        - Path=/accounts/**
        filters:
        - name: FallbackPath
          args:
            retainRequestPath: true
        - name: ErrorCodeToException
        - name: CircuitBreaker
          args:
            name: svc-fallback
            fallbackUri: forward:/fallback
      - id: user-service
        uri: ${USER_EP}
        predicates:
        - Path=/users/**
        filters:
        - name: FallbackPath
          args:
            retainRequestPath: true
        - name: CircuitBreaker
          args:
            name: svc-fallback
            fallbackUri: forward:/fallback
      - id: user-service-login
        uri: ${USER_EP}
        predicates:
        - Path=/login/**
        filters:
        - name: FallbackPath
          args:
            retainRequestPath: true
        - name: CircuitBreaker
          args:
            name: svc-fallback
            fallbackUri: forward:/fallback
      - id: user-service-logout
        uri: ${USER_EP}
        predicates:
        - Path=/logout/**
        filters:
        - name: FallbackPath
          args:
            retainRequestPath: true
        - name: CircuitBreaker
          args:
            name: svc-fallback
            fallbackUri: forward:/fallback
      - id: portfolio-service
        uri: ${PORTFOLIO_EP}
        predicates:
        - Path=/portfolio/**
        filters:
        - name: FallbackPath
          args:
            retainRequestPath: true
        - name: CircuitBreaker
          args:
            name: svc-fallback
            fallbackUri: forward:/fallback
      - id: analytics-service
        uri: ${ANALYTICS_EP}
        predicates:
        - Path=/analytics/**
        #filters:
        #- RewritePath=/analytics/(?<path>.*), /$\{path}
      - id: svc-fallback
        uri: ${CROSSPLANE_EP}
        predicates:
          - Path=/fallback
        filters:
        - name: FallbackPath
          args:
            suffixPath: true
        - StripPrefix=1
  sleuth:
    enabled: true
    sampler.probability: 1
  zipkin:
    enabled: true

wavefront:
  application:
    service: gateway-service

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
