spring:
  application:
     name: web-service
#eureka:
#  client:
#    registerWithEureka: true
#    registryFetchIntervalSeconds: 10
pivotal:
  summary:
    quotes: 4
    symbols:
      it: ORCL,VMW,INTC,AMD,HPQ,CSCO,AAPL
      fs: JPM,C,MS,BAC,GS,WFC,BK
    refresh: 3600000
wavefront:
  application:
    service: web-service
