info:
  component: Config Server
spring:
  application:
    name: regional-config-service
#  profiles:
#    active: native
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
#        native:
#          searchLocations: file:${user.dir}/../cf-SpringBootTrader-config
# If you want to point to the main git,
#  then comment out spring.profiles.active and spring.cloud.config.server.native
#  and uncomment spring.cloud.config.server.git
        git:
          uri: https://github.com/srinivasa-vasu/tanzu-bank-distributed.git
          searchPaths: regional-svc/config
#          default-label: pks_1.0
management:
  context_path: /admin
#server:
#  port: 8888
