---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "web"
spec:
  template:
    spec:
      initContainers:
      - name: init-config-check
        image: busybox:latest
        command:
        - '/bin/sh'
        - '-c'
        - |
          while true
          do
            rt=$(nc -z -w 1 gateway-service 80)
            if [ $? -eq 0 ]; then
              echo "Gateway service is UP"
              break
            fi
            echo "Gateway service is not yet reachable;sleep for 5s before retry"
            sleep 5
          done      
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "web-service"
    version: "1.0"
  name: "web-service"
spec:
  ports:
  - name: "web"
    port: 80
    targetPort: 8080
    nodePort: 32001
  selector:
    app: "web"
    version: "1.0"
  type: "LoadBalancer"
  loadBalancerIP: 10.195.9.189
