apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "regional-gateway-service"
    version: "1.0"
  name: "regional-gateway-service"
spec:
  ports:
    - name: "web"
      port: 80
      targetPort: 8080
      nodePort: 32000
  selector:
    app: "gateway"
    version: "1.0"
  type: "LoadBalancer"
  loadBalancerIP: 10.195.9.200
