apiVersion: v1
kind: ConfigMap
metadata:
  name: ds-props
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://10.195.9.59:31000/traderdb?useUnicode=true&characterEncoding=utf8&useSSL=false
  SPRING_DATASOURCE_USERNAME: root
  host: 10.195.9.59
  port: "31000"
#  SPRING_DATASOURCE_URL: jdbc:mysql://traderdb.bank.tanzu:3306/traderdb?useUnicode=true&characterEncoding=utf8&useSSL=false
#  SPRING_DATASOURCE_USERNAME: root
#  host: traderdb.bank.tanzu
#  port: "3306"
