spring:
  application:
    name: crossplane-service
  cloud:
    discovery:
      enabled: true
      blocking:
        enabled: false
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: cb-fallback
          uri: ${CP_GW_EP}
          predicates:
            - Path=/accounts/**,/portfolio/**,/logout/**,/login/**,/users/**
        - id: any-request # regional-svc gateway
          uri: ${CP_RGW_EP}
          predicates:
            - Path=/**
  sleuth:
    enabled: true
    sampler.probability: 1
  zipkin:
    enabled: true
wavefront:
  application:
    service: ${CP_NAME}


#logging:
#  level:
#    reactor:
#      netty: INFO
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
