---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traderdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traderdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traderdb
  template:
    metadata:
      labels:
        app: traderdb
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: traderdb-pvc
      containers:
      - name: mysql
        image: mysql:8.0.16
        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: 'yes'
        - name: MYSQL_DATABASE
          value: traderdb
        args:
        - --lower_case_table_names=1
        - --skip-ssl
        - --character_set_server=utf8mb4
        - --explicit_defaults_for_timestamp
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/data/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: traderdb
spec:
  type: NodePort
  selector:
    app: traderdb
  ports:
    - name: jdbc
      port: 3306
      nodePort: 31000
