---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "gateway"
    kind: "k8s-native"
    version: "1.0"
  name: "gateway"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "gateway"
      kind: "k8s-native"
      version: "1.0"
  template:
    metadata:
      labels:
        app: "gateway"
        kind: "k8s-native"
        version: "1.0"
    spec:
      serviceAccountName: boot-sa
      containers:
      - name: "gateway"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "sleep 10"]
        envFrom:
        - configMapRef:
            name: config-props
        image: "harbor.sys.humourmind.com/tanzumc/gateway-rsvc:1.0"
        imagePullPolicy: "Always"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/health/readiness"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/health/liveness"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        ports:
        - containerPort: 8080
          name: "web"
          protocol: "TCP"
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "regional-gateway-service"
    version: "1.0"
  name: "regional-gateway-service"
spec:
  ports:
  - name: "web"
    port: 80
    targetPort: 8080
    nodePort: 32000
  selector:
    app: "gateway"
    version: "1.0"
  type: "LoadBalancer"
  loadBalancerIP: 10.195.9.200
