apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: crossplane
      context: ../../apac/crossplane-service
      buildpack:
        builder: humourmind/paketo-java-builder-tiny:0.7.3
    - image: gateway
      context: ../../apac/gateway-service
      buildpack:
        builder: humourmind/paketo-java-builder-tiny:0.7.3
    - image: portfolio
      context: ../../apac/portfolio-service
      buildpack:
        builder: humourmind/paketo-java-builder-tiny:0.7.3
    - image: accounts
      context: ../../apac/accounts-service
      buildpack:
        builder: humourmind/paketo-java-builder-tiny:0.7.3
    - image: quotes
      context: ../../apac/quotes-service
      buildpack:
        builder: humourmind/paketo-java-builder-tiny:0.7.3
    - image: user
      context: ../../apac/user-service
      buildpack:
        builder: humourmind/paketo-java-builder-tiny:0.7.3
    - image: web
      context: ../../apac/web-ui
      buildpack:
        builder: humourmind/paketo-java-builder-tiny:0.7.3
  tagPolicy:
    envTemplate:
      template: 'harbor.sys.humourmind.com/tanzumc/{{.IMAGE_NAME}}:1.0'
  local:
    push: true
deploy:
  kustomize: {}
