---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "gateway-service"
    version: "1.0"
  name: "as-gateway-service"
spec:
  ports:
    - name: "web"
      port: 80
      targetPort: 8080
  selector:
    app: "gateway"
    version: "1.0"
